### ISSUE TITLE
Consolidate links

### ISSUE THREAD

**Issue by Frozenfire92** [SMUCSM/TMHTBluemix#1]
We have gone through a lot of documentation, tutorials, and other useful links. It would be nice to have a file in this repository that loosely annotated them.

I was thinking `/links/README.md` and then adding them with brief descriptions

**Comment by Glavin001** [comment]
_Post bomb coming soon._

**Comment by Glavin001** [comment]
- https://www.ng.bluemix.net/docs/#services/Auto-Scaling/index.html#autoscaling 
- Watson REST API docs - http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/apis/ 
- Doctor Watson - https://github.com/IBM-Bluemix/doctor-watson
- Create a natural language question answering system with IBM Watson and Bluemix services - http://www.ibm.com/developerworks/cloud/library/cl-watson-films-bluemix-app/
- Getting Started with AlchemyAPI Using Node.js - http://www.alchemyapi.com/developers/getting-started-guide/using-alchemyapi-with-nodejs
- alchemy-api npm package - https://www.npmjs.com/package/alchemy-api 
- bluemix related npm packages - https://www.npmjs.com/search?q=bluemix 
- askwatson (Watson npm package) - https://www.npmjs.com/package/askwatson
- blue package on npm - https://www.npmjs.com/package/bluemix
- Tradeoff analytics demo - http://tradeoff-analytics-demo.mybluemix.net/
- AlchemyAPI Demos -  http://www.alchemyapi.com/products/demo
- text to speech demo - http://text-to-speech-demo.mybluemix.net/
- speech to text demo - https://speech-to-text-demo.mybluemix.net/
- watson developer cloud - https://github.com/watson-developer-cloud
- bluemix command line interface - https://www.ng.bluemix.net/docs/#cli/cli.html#cli
- sample question and answer app in node.js - http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/qaapi/#nodejsApplication
- https://github.com/ibmjstart/bluemix-python-sample-twitter-influence-app
